### ISSUE TITLE
How to translate Showing 1 to 1 of 1 entries and pagination "Previous, Next"

### ISSUE THREAD

**Issue by xillibit** [cobaltcrm/cobalt#114]
By example if i go into companies menu or deals menu, i have in the bottom "Showing 1 to 1 of 1 entries" but i found anywhere where are this hard-coded to translate them. It's the same with pagination it seems that the button "Previous, Next" are hard-coded. It's the same with "No data available in table"

Can-you tell me in which files can-i found these strings ?

**Comment by escopecz** [comment]
Cobalt uses jQuery dataTables. You can read how to translate them at http://datatables.net/plug-ins/i18n/

**Comment by xillibit** [comment]
In which directory the translations files for datatables should be stored ?

**Comment by escopecz** [comment]
In my opinion, it would be better to use language definitions directly like this:

```
$('#example').dataTable( {
    "language": {
        "lengthMenu": "Display _MENU_ records per page",
        "zeroRecords": "Nothing found - sorry",
        "info": "Showing page _PAGE_ of _PAGES_",
        "infoEmpty": "No records available",
        "infoFiltered": "(filtered from _MAX_ total records)"
    }
} );
```

Instead of hard coded strings use 

```
"lengthMenu": Joomla.JText._("COBALT_DATATABLE_RECORDS_PER_PAGE"),
```

At EN language file define:

```
COBALT_DATATABLE_RECORDS_PER_PAGE="Display _MENU_ records per page"
```

And at other language files translate it as we are used to. To use this language string at JS, you have to add it to TemplateHelper.
This approach has advantage that all language strings will be in one file which can be translated at https://www.transifex.com/organization/allyde/dashboard/cobaltcrm
